version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/codedeploy/r6-community/
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  AfterInstall:
    - location: deploy_commuunity.sh
      timeout: 60
      runas: root